apiVersion: v1
kind: Service
metadata:
  name: vv
  labels:
    app: vv
    service: vv
spec:
  selector:
    app: vv
    service: vv
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP